SELECT * FROM DEPARTMENTS;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE SALARY > 15000;

LAST_NAME FROM EMPLOYEES WHERE HIRE_DATE >= TO_DATE('January 01, 2002', 'MONTH DD, YYYY')  AND HIRE_DATE <= TO_DATE('January 01, 2004', 'MONTH DD, YYYY');

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE PHONE_NUMBER NOT LIKE '515%';

SELECT FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID = 100 ORDER BY FIRST_NAME;

SELECT CITY, STATE_PROVINCE, COUNTRY_NAME FROM LOCATIONS, COUNTRIES WHERE LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID AND COUNTRIES.REGION_ID = 3;

SELECT CITY, STATE_PROVINCE FROM LOCATIONS WHERE STATE_PROVINCE IS NULL;

