--Data
INSERT INTO Artist VALUES (1, 'Adele');
INSERT INTO Artist VALUES (2, 'Beyonce');
INSERT INTO Artist VALUES (3, 'Lukas Graham');
INSERT INTO Artist VALUES (4, 'Rihanna');
INSERT INTO Artist VALUES (5, 'Drake');
INSERT INTO Artist VALUES (6, 'Twenty One Pilots');
INSERT INTO Artist VALUES (7, 'Justin Bieber');
INSERT INTO Artist VALUES (8, 'Sturgill Simpson');
INSERT INTO Artist VALUES (9, 'Chance The Rapper');
INSERT INTO Artist VALUES (10, 'Kelsea Ballerini');
INSERT INTO Artist VALUES (11, 'The Chainsmokers');
INSERT INTO Artist VALUES (12, 'Maren Morris');
INSERT INTO Artist VALUES (13, 'Anderson .Paak');


INSERT INTO Label VALUES (1, 'Columbia Records');
INSERT INTO Label VALUES (2, 'ISO');
INSERT INTO Label VALUES (3, 'DCD2');
INSERT INTO Label VALUES (4, 'Fueled By Ramen');
INSERT INTO Label VALUES (5, 'XL Recordings');
INSERT INTO Label VALUES (6, 'Walt Disney Records');
INSERT INTO Label VALUES (7, 'Republic Records');
INSERT INTO Label VALUES (8, 'Parkwood Entertainment');
INSERT INTO Label VALUES (9, 'Warner Bro. Records');
INSERT INTO Label VALUES (10, 'Westbury Road Entertainment');
INSERT INTO Label VALUES (11, 'Def Jam Recordings');
INSERT INTO Label VALUES (12, 'Young Money');
INSERT INTO Label VALUES (13, 'Cash Money');
INSERT INTO Label VALUES (14, 'Atlantic');


INSERT INTO Person VALUES (1, 'Greg', 'Kurstin', null);
INSERT INTO Person VALUES (2, 'Julian', 'Burg', null);
INSERT INTO Person VALUES (3, 'Tom', 'Elmhirst', null);
INSERT INTO Person VALUES (4, 'Emile', 'Haynie', null);
INSERT INTO Person VALUES (5, 'Liam', 'Nolan', null);
INSERT INTO Person VALUES (6, 'Alex', 'Pasco', null);
INSERT INTO Person VALUES (7, 'Joe', 'Visciano', null);
INSERT INTO Person VALUES (8, 'Tom', 'Coyne', null);
INSERT INTO Person VALUES (9, 'Randy', 'Merrill', null);
INSERT INTO Person VALUES (10, null, null, 'Danger Mouse');
INSERT INTO Person VALUES (11, 'Mike', 'Elizondo', null);
INSERT INTO Person VALUES (12, 'Tyler', 'Joseph', null);
INSERT INTO Person VALUES (13, 'Neal', 'Avron', null);
INSERT INTO Person VALUES (14, 'Adam', 'Hawkins', null);
INSERT INTO Person VALUES (15, 'Chris', 'Gehringer', null);
INSERT INTO Person VALUES (16, 'Samuel', 'Dixon', null);
INSERT INTO Person VALUES (17, 'Beyonce', 'Knowles', null);
INSERT INTO Person VALUES (18, 'Michael', 'Williams II', 'Mike Will Made-It');
INSERT INTO Person VALUES (19, null, null, 'Pluss');
INSERT INTO Person VALUES (20, 'Jaycen', 'Joshua', null);
INSERT INTO Person VALUES (21, 'Stuart', 'White', null);
INSERT INTO Person VALUES (22, 'Dave', 'Kutch', null);
INSERT INTO Person VALUES (23, null, null, 'Future Animals');
INSERT INTO Person VALUES (24, null, null, 'Pilo');
INSERT INTO Person VALUES (25, 'Delbert', 'Bowers', null);
INSERT INTO Person VALUES (26, 'Sebastian', 'Fogh', null);
INSERT INTO Person VALUES (27, 'Stefan', 'Forrest', null);
INSERT INTO Person VALUES (28, 'David', 'LaBrel', null);
INSERT INTO Person VALUES (29, 'Paul', 'Epworth', null);
INSERT INTO Person VALUES (30, null, null, 'Boi-1da');
INSERT INTO Person VALUES (31, 'Noel', 'Campbell', 'Gadget');
INSERT INTO Person VALUES (32, 'Kuk', 'Harrell', null);
INSERT INTO Person VALUES (33, 'Manny', 'Marroquin', null);
INSERT INTO Person VALUES (34, 'Noah', 'Shebib', '40');
INSERT INTO Person VALUES (35, 'Marcos', 'Tovar', null);
INSERT INTO Person VALUES (36, 'Max', 'Martin', null);
INSERT INTO Person VALUES (37, 'Ariel', 'Rechtshaid', null);
INSERT INTO Person VALUES (38, null, null, 'Shellback');
INSERT INTO Person VALUES (39, null, null, 'The Smeezingtons');
INSERT INTO Person VALUES (40, 'Ryan', 'Tedder', null);
INSERT INTO Person VALUES (41, 'Julian', 'Burg', null);
INSERT INTO Person VALUES (42, 'Austen', 'Chandler', null);
INSERT INTO Person VALUES (43, 'Cameron', 'Craig', null);
INSERT INTO Person VALUES (44, 'Charles', 'Moniz', null);
INSERT INTO Person VALUES (45, 'Declan', 'Gafney', null);
INSERT INTO Person VALUES (46, 'Serban', 'Ghenea', null);
INSERT INTO Person VALUES (47, 'John', 'Hanes', null);
INSERT INTO Person VALUES (48, 'Mike', 'Piersante', null);
INSERT INTO Person VALUES (49, 'Jan', 'Holzner', null);
INSERT INTO Person VALUES (50, 'Michael', 'Ilbert', null);
INSERT INTO Person VALUES (51, 'Chris', 'Kasich', null);
INSERT INTO Person VALUES (52, 'Rich', 'Rich', null);
INSERT INTO Person VALUES (53, 'Dave', 'Schiffman', null);
INSERT INTO Person VALUES (54, 'Matt', 'Wiggins', null);
INSERT INTO Person VALUES (55, 'James', 'Blake', null);
INSERT INTO Person VALUES (56, 'Kendrick', 'Lamar', null);
INSERT INTO Person VALUES (57, null, null, 'The Weeknd');
INSERT INTO Person VALUES (58, 'Jack', 'White', null);
INSERT INTO Person VALUES (59, 'Vincent', 'Berry II', null);
INSERT INTO Person VALUES (60, 'Ben', 'Billions', null);
INSERT INTO Person VALUES (61, null, null, 'BOOTS');
INSERT INTO Person VALUES (62, 'Jonny', 'Coffer', null);
INSERT INTO Person VALUES (63, null, null, 'Dannyboystyles');
INSERT INTO Person VALUES (64, 'Michael', 'Dean', null);
INSERT INTO Person VALUES (65, 'Alex', 'Delicata', null);
INSERT INTO Person VALUES (66, null, null, 'Diplo');
INSERT INTO Person VALUES (67, 'Derek', 'Dixie', null);
INSERT INTO Person VALUES (68, 'Kevin', 'Garrett', null);
INSERT INTO Person VALUES (69, 'Diana', 'Gordon', null);
INSERT INTO Person VALUES (70, null, null, 'HazeBanga');
INSERT INTO Person VALUES (71, null, null, 'Hit-Boy');
INSERT INTO Person VALUES (72, null, null, 'Just Blaze');
INSERT INTO Person VALUES (73, null, null, 'King Henry');
INSERT INTO Person VALUES (74, 'Ezra', 'Koenig', null);
INSERT INTO Person VALUES (75, 'Jeremy', 'McDonald', null);
INSERT INTO Person VALUES (76, null, null, 'MeLo-X');
INSERT INTO Person VALUES (77, 'Malik', 'Yusuf', null);
INSERT INTO Person VALUES (78, 'Mike', 'Dean', null);
--Person 79
INSERT INTO Person VALUES (80, 'Greg', 'Koller', null);
INSERT INTO Person VALUES (81, 'Tony', 'Maserati', null);
INSERT INTO Person VALUES (82, 'Lester', 'Mendoza', null);
INSERT INTO Person VALUES (83, 'Vance', 'Powell', null);
INSERT INTO Person VALUES (84, 'Joshua', 'Smith', null);
INSERT INTO Person VALUES (85, null, null, 'Big Sean');
INSERT INTO Person VALUES (86, null, null, 'Halsey');
INSERT INTO Person VALUES (87, 'Travis', 'Scott', null);
INSERT INTO Person VALUES (88, null, null, 'Skrillex');
INSERT INTO Person VALUES (89, null, null, 'The Audibles');
INSERT INTO Person VALUES (90, null, null, 'Axident');
INSERT INTO Person VALUES (91, 'Justin', 'Bieber', null);
INSERT INTO Person VALUES (92, null, null, 'Big Taste');
INSERT INTO Person VALUES (93, 'Benny', 'Blanco', null);
INSERT INTO Person VALUES (94, null, null, 'Blood');
INSERT INTO Person VALUES (95, 'Jason', 'Boyd', 'Poo Bear');
INSERT INTO Person VALUES (96, 'Scott', 'Braun', 'Scooter');
INSERT INTO Person VALUES (97, null, null, 'Gladius');
INSERT INTO Person VALUES (98, 'Josh', 'Gudwin', null);
INSERT INTO Person VALUES (99, 'Nico', 'Hartikainen', null);
INSERT INTO Person VALUES (100, 'Mark', 'Jackson', 'The Mogul');
INSERT INTO Person VALUES (101, 'Steve', 'James', null);
INSERT INTO Person VALUES (102, 'Ian', 'Kirkpatrick', null);
INSERT INTO Person VALUES (103, null, null, 'Maejor');
INSERT INTO Person VALUES (104, null, null, 'MdL');
INSERT INTO Person VALUES (105, 'Jeremy', 'Snyder', null);
INSERT INTO Person VALUES (106, null, null, chr(38) || ' S O U N D Z');
INSERT INTO Person VALUES (107, 'Simon', 'Cohen', null);
INSERT INTO Person VALUES (108, 'Joshua', 'Connolly', null);
INSERT INTO Person VALUES (109, 'Mark', 'Goodchild', 'Exit');
INSERT INTO Person VALUES (110, 'Chris', 'O''Ryan', 'Tek');
INSERT INTO Person VALUES (111, 'Johannes', 'Raassina', null);
INSERT INTO Person VALUES (112, 'Gregg', 'Rominiecki', null);
INSERT INTO Person VALUES (113, 'Bart', 'Schoudel', null);
INSERT INTO Person VALUES (114, 'Chris', 'Sclafani', null);
INSERT INTO Person VALUES (115, 'Dylan', 'William', null);
INSERT INTO Person VALUES (116, 'Andrew', 'Wuepper', null);
INSERT INTO Person VALUES (117, null, null, 'dvs');
INSERT INTO Person VALUES (118, null, null, 'Future');
INSERT INTO Person VALUES (119, null, null, 'Kyla');
INSERT INTO Person VALUES (120, null, null, 'PARTYNEXTDOOR');
INSERT INTO Person VALUES (121, null, null, 'Rihanna');
INSERT INTO Person VALUES (122, null, null, 'Wizkid');
INSERT INTO Person VALUES (123, 'Brian', 'Alexander-Morgan', null);
INSERT INTO Person VALUES (124, null, null, 'Axlfoliethc');
INSERT INTO Person VALUES (125, null, null, 'Beat Bully');
INSERT INTO Person VALUES (126, null, null, 'Cardo');
INSERT INTO Person VALUES (127, 'Dwayne', 'Chin-Quee', 'Supa Dups');
INSERT INTO Person VALUES (128, null, null, 'Daxz');
INSERT INTO Person VALUES (129, null, null, 'DJ Dahi');
INSERT INTO Person VALUES (130, 'Frank', 'Dukes', null);
INSERT INTO Person VALUES (131, null, null, 'Maneesh');
INSERT INTO Person VALUES (132, null, null, 'Murda Beatz');
INSERT INTO Person VALUES (133, null, null, 'Nineteen85');
INSERT INTO Person VALUES (134, 'Ricci', 'Riera', null);
INSERT INTO Person VALUES (135, 'Allen', 'Ritter', null);
INSERT INTO Person VALUES (136, null, null, 'Southside');
INSERT INTO Person VALUES (137, 'Sevn', 'Thomas', null);
INSERT INTO Person VALUES (138, 'Jordan', 'Ullman', null);
INSERT INTO Person VALUES (139, 'Kanye', 'West', null);
INSERT INTO Person VALUES (140, null, null, 'Young Exclusive');
INSERT INTO Person VALUES (141, 'Noel', 'Cadastre', null);
INSERT INTO Person VALUES (142, 'Seth', 'Firkins', null);
INSERT INTO Person VALUES (143, 'David', 'Bijan Hughes', 'Prep');
INSERT INTO Person VALUES (144, 'Chris', 'Athens', null);
INSERT INTO Person VALUES (145, 'Sturgill', 'Simpson', null);
INSERT INTO Person VALUES (146, 'Geoff', 'Allan', null);
INSERT INTO Person VALUES (147, 'David', 'Ferguson', null);
INSERT INTO Person VALUES (148, 'Sean', 'Sullivan', null);
INSERT INTO Person VALUES (149, 'Gavin', 'Lurssen', null);



INSERT INTO Album VALUES (1, 1, '25', 2016);
INSERT INTO Album VALUES (2, 2, 'Lemonade', 2016);
INSERT INTO Album VALUES (3, 3, 'Lukas Graham', 2016);
INSERT INTO Album VALUES (4, 6, 'Blurryface', 2016);
INSERT INTO Album VALUES (5, 7, 'Purpose', 2016);
INSERT INTO Album VALUES (6, 5, 'Views', 2016);
INSERT INTO Album VALUES (7, 8, 'A Sailor''s Guide to Earth', 2016);



INSERT INTO Song VALUES (1, 1, 'Hello', 2016);
INSERT INTO Song VALUES (2, 2, 'Formation', 2016);
INSERT INTO Song VALUES (3, 3, '7 Years', 2016);
INSERT INTO Song VALUES (4, null, 'Work', 2016);
INSERT INTO Song VALUES (5, 4, 'Stressed Out', 2016);



INSERT INTO AlbumLabel VALUES (1, 1);
INSERT INTO AlbumLabel VALUES (1, 5);
INSERT INTO AlbumLabel VALUES (2, 1);
INSERT INTO AlbumLabel VALUES (2, 8);
INSERT INTO AlbumLabel VALUES (3, 9);
INSERT INTO AlbumLabel VALUES (4, 4);
INSERT INTO AlbumLabel VALUES (5, 11);
INSERT INTO AlbumLabel VALUES (6, 12);
INSERT INTO AlbumLabel VALUES (6, 13);
INSERT INTO AlbumLabel VALUES (6, 7);
INSERT INTO AlbumLabel VALUES (7, 14);


INSERT INTO SongLabel VALUES (4, 10);


INSERT INTO AlbumPerson VALUES(1, 10, 'producer');
INSERT INTO AlbumPerson VALUES(1, 16, 'producer');
INSERT INTO AlbumPerson VALUES(1, 29, 'producer');
INSERT INTO AlbumPerson VALUES(1, 1, 'producer');
INSERT INTO AlbumPerson VALUES(1, 36, 'producer');
INSERT INTO AlbumPerson VALUES(1, 37, 'producer');
INSERT INTO AlbumPerson VALUES(1, 38, 'producer');
INSERT INTO AlbumPerson VALUES(1, 39, 'producer');
INSERT INTO AlbumPerson VALUES(1, 40, 'producer');
INSERT INTO AlbumPerson VALUES(1, 41, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 42, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 43, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 3, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 45, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 46, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 47, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 4, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 49, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 50, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 51, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 1, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 44, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 5, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 6, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 48, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 37, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 52, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 53, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 7, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 54, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(1, 8, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(1, 9, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(2, 55, 'featured artist');
INSERT INTO AlbumPerson VALUES(2, 56, 'featured artist');
INSERT INTO AlbumPerson VALUES(2, 57, 'featured artist');
INSERT INTO AlbumPerson VALUES(2, 58, 'featured artist');
INSERT INTO AlbumPerson VALUES(2, 59, 'producer');
INSERT INTO AlbumPerson VALUES(2, 60, 'producer');
INSERT INTO AlbumPerson VALUES(2, 55, 'producer');
INSERT INTO AlbumPerson VALUES(2, 61, 'producer');
INSERT INTO AlbumPerson VALUES(2, 62, 'producer');
INSERT INTO AlbumPerson VALUES(2, 63, 'producer');
INSERT INTO AlbumPerson VALUES(2, 64, 'producer');
INSERT INTO AlbumPerson VALUES(2, 65, 'producer');
INSERT INTO AlbumPerson VALUES(2, 66, 'producer');
INSERT INTO AlbumPerson VALUES(2, 67, 'producer');
INSERT INTO AlbumPerson VALUES(2, 68, 'producer');
INSERT INTO AlbumPerson VALUES(2, 69, 'producer');
INSERT INTO AlbumPerson VALUES(2, 70, 'producer');
INSERT INTO AlbumPerson VALUES(2, 71, 'producer');
INSERT INTO AlbumPerson VALUES(2, 72, 'producer');
INSERT INTO AlbumPerson VALUES(2, 73, 'producer');
INSERT INTO AlbumPerson VALUES(2, 17, 'producer');
INSERT INTO AlbumPerson VALUES(2, 74, 'producer');
INSERT INTO AlbumPerson VALUES(2, 75, 'producer');
INSERT INTO AlbumPerson VALUES(2, 76, 'producer');
INSERT INTO AlbumPerson VALUES(2, 18, 'producer');
INSERT INTO AlbumPerson VALUES(2, 19, 'producer');
INSERT INTO AlbumPerson VALUES(2, 58, 'producer');
INSERT INTO AlbumPerson VALUES(2, 77, 'producer');
INSERT INTO AlbumPerson VALUES(2, 78, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 20, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 80, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 81, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 82, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 83, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 84, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 21, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(2, 22, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(5, 85, 'featured artist');
INSERT INTO AlbumPerson VALUES(5, 86, 'featured artist');
INSERT INTO AlbumPerson VALUES(5, 87, 'featured artist');
INSERT INTO AlbumPerson VALUES(5, 88, 'featured artist');
INSERT INTO AlbumPerson VALUES(5, 89, 'producer');
INSERT INTO AlbumPerson VALUES(5, 90, 'producer');
INSERT INTO AlbumPerson VALUES(5, 91, 'producer');
INSERT INTO AlbumPerson VALUES(5, 92, 'producer');
INSERT INTO AlbumPerson VALUES(5, 93, 'producer');
INSERT INTO AlbumPerson VALUES(5, 94, 'producer');
INSERT INTO AlbumPerson VALUES(5, 95, 'producer');
INSERT INTO AlbumPerson VALUES(5, 96, 'producer');
INSERT INTO AlbumPerson VALUES(5, 78, 'producer');
INSERT INTO AlbumPerson VALUES(5, 66, 'producer');
INSERT INTO AlbumPerson VALUES(5, 20, 'producer');
INSERT INTO AlbumPerson VALUES(5, 33, 'producer');
INSERT INTO AlbumPerson VALUES(5, 97, 'producer');
INSERT INTO AlbumPerson VALUES(5, 98, 'producer');
INSERT INTO AlbumPerson VALUES(5, 99, 'producer');
INSERT INTO AlbumPerson VALUES(5, 100, 'producer');
INSERT INTO AlbumPerson VALUES(5, 101, 'producer');
INSERT INTO AlbumPerson VALUES(5, 102, 'producer');
INSERT INTO AlbumPerson VALUES(5, 103, 'producer');
INSERT INTO AlbumPerson VALUES(5, 104, 'producer');
INSERT INTO AlbumPerson VALUES(5, 105, 'producer');
INSERT INTO AlbumPerson VALUES(5, 106, 'producer');
INSERT INTO AlbumPerson VALUES(5, 88, 'producer');
INSERT INTO AlbumPerson VALUES(5, 107, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 108, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 109, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 110, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 111, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 112, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 113, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 114, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 115, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 116, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 66, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 98, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 20, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 33, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(5, 8, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(5, 9, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(6, 117, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 118, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 119, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 120, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 121, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 122, 'featured artist');
INSERT INTO AlbumPerson VALUES(6, 123, 'producer');
INSERT INTO AlbumPerson VALUES(6, 124, 'producer');
INSERT INTO AlbumPerson VALUES(6, 125, 'producer');
INSERT INTO AlbumPerson VALUES(6, 126, 'producer');
INSERT INTO AlbumPerson VALUES(6, 127, 'producer');
INSERT INTO AlbumPerson VALUES(6, 128, 'producer');
INSERT INTO AlbumPerson VALUES(6, 129, 'producer');
INSERT INTO AlbumPerson VALUES(6, 130, 'producer');
INSERT INTO AlbumPerson VALUES(6, 131, 'producer');
INSERT INTO AlbumPerson VALUES(6, 132, 'producer');
INSERT INTO AlbumPerson VALUES(6, 133, 'producer');
INSERT INTO AlbumPerson VALUES(6, 134, 'producer');
INSERT INTO AlbumPerson VALUES(6, 135, 'producer');
INSERT INTO AlbumPerson VALUES(6, 136, 'producer');
INSERT INTO AlbumPerson VALUES(6, 137, 'producer');
INSERT INTO AlbumPerson VALUES(6, 138, 'producer');
INSERT INTO AlbumPerson VALUES(6, 139, 'producer');
INSERT INTO AlbumPerson VALUES(6, 140, 'producer');
INSERT INTO AlbumPerson VALUES(6, 30, 'producer');
INSERT INTO AlbumPerson VALUES(6, 34, 'producer');
INSERT INTO AlbumPerson VALUES(6, 122, 'producer');
INSERT INTO AlbumPerson VALUES(6, 141, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(6, 142, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(6, 143, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(6, 31, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(6, 34, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(6, 144, 'mastering engineer');
INSERT INTO AlbumPerson VALUES(7, 145, 'producer');
INSERT INTO AlbumPerson VALUES(7, 146, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(7, 147, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(7, 148, 'engineer/mixer');
INSERT INTO AlbumPerson VALUES(7, 149, 'mastering engineer');



INSERT INTO SongPerson VALUES (1, 1, 'producer');
INSERT INTO SongPerson VALUES (1, 1, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 2, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 3, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 4, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 5, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 6, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 7, 'engineer/mixer');
INSERT INTO SongPerson VALUES (1, 8, 'mastering engineer');
INSERT INTO SongPerson VALUES (1, 9, 'mastering engineer');
INSERT INTO SongPerson VALUES (2, 17, 'producer');
INSERT INTO SongPerson VALUES (2, 18, 'producer');
INSERT INTO SongPerson VALUES (2, 19, 'producer');
INSERT INTO SongPerson VALUES (2, 20, 'engineer/mixer');
INSERT INTO SongPerson VALUES (2, 21, 'engineer/mixer');
INSERT INTO SongPerson VALUES (2, 22, 'mastering engineer');
INSERT INTO SongPerson VALUES (3, 23, 'producer');
INSERT INTO SongPerson VALUES (3, 24, 'producer');
INSERT INTO SongPerson VALUES (3, 25, 'engineer/mixer');
INSERT INTO SongPerson VALUES (3, 26, 'engineer/mixer');
INSERT INTO SongPerson VALUES (3, 27, 'engineer/mixer');
INSERT INTO SongPerson VALUES (3, 28, 'engineer/mixer');
INSERT INTO SongPerson VALUES (3, 8, 'mastering engineer');
INSERT INTO SongPerson VALUES (4, 30, 'producer');
INSERT INTO SongPerson VALUES (4, 31, 'engineer/mixer');
INSERT INTO SongPerson VALUES (4, 32, 'engineer/mixer');
INSERT INTO SongPerson VALUES (4, 33, 'engineer/mixer');
INSERT INTO SongPerson VALUES (4, 34, 'engineer/mixer');
INSERT INTO SongPerson VALUES (4, 35, 'engineer/mixer');
INSERT INTO SongPerson VALUES (4, 15, 'mastering engineer');
INSERT INTO SongPerson VALUES (5, 11, 'producer');
INSERT INTO SongPerson VALUES (5, 12, 'producer');
INSERT INTO SongPerson VALUES (5, 13, 'engineer/mixer');
INSERT INTO SongPerson VALUES (5, 14, 'engineer/mixer');
INSERT INTO SongPerson VALUES (5, 15, 'mastering engineer');



INSERT INTO ArtistSong VALUES (1, 1, 'artist');
INSERT INTO ArtistSong VALUES (2, 2, 'artist');
INSERT INTO ArtistSong VALUES (3, 3, 'artist');
INSERT INTO ArtistSong VALUES (4, 4, 'artist');
INSERT INTO ArtistSong VALUES (5, 4, 'featured artist');
INSERT INTO ArtistSong VALUES (6, 5, 'artist');








INSERT INTO Award VALUES (1, 'Record of the Year', 2016, 'winner', 0, null, 1, null);
INSERT INTO Award VALUES (2, 'Record of the Year', 2016, 'nominee', 0, null, 2, null);
INSERT INTO Award VALUES (3, 'Record of the Year', 2016, 'nominee', 0, null, 3, null);
INSERT INTO Award VALUES (4, 'Record of the Year', 2016, 'nominee', 0, null, 4, null);
INSERT INTO Award VALUES (5, 'Record of the Year', 2016, 'nominee', 0, null, 5, null);
INSERT INTO Award VALUES (6, 'Album of the Year', 2016, 'winner', 0, 1, null, null);
INSERT INTO Award VALUES (7, 'Album of the Year', 2016, 'nominee', 0, 2, null, null);
INSERT INTO Award VALUES (8, 'Album of the Year', 2016, 'nominee', 0, 5, null, null);
INSERT INTO Award VALUES (9, 'Album of the Year', 2016, 'nominee', 0, 6, null, null);
INSERT INTO Award VALUES (10, 'Album of the Year', 2016, 'nominee', 0, 7, null, null);
INSERT INTO Award VALUES (11, 'Best New Artist', 2016, 'winner', 0, null, null, 9);
INSERT INTO Award VALUES (12, 'Best New Artist', 2016, 'nominee', 0, null, null, 10);
INSERT INTO Award VALUES (13, 'Best New Artist', 2016, 'nominee', 0, null, null, 11);
INSERT INTO Award VALUES (14, 'Best New Artist', 2016, 'nominee', 0, null, null, 12);
INSERT INTO Award VALUES (15, 'Best New Artist', 2016, 'nominee', 0, null, null, 13);






